version: '3.7'
volumes:
  mysql_data:
    driver: local
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    restart: always
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
  kafka-broker:
    image: confluentinc/cp-kafka:latest
    restart: always
    container_name: kafka
    hostname: kafka-broker
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker:9092,LISTENER_LOCAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,LISTENER_LOCAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  db_mysql:
   image: mysql:5.7.25
   container_name: mysql
   hostname: mysql
   restart: always
   environment:
     - MYSQL_DATABASE=SOURCE_DB
     - MYSQL_ROOT_PASSWORD=123456
   ports:
     - '3306:3306'
  db_postgres:     
   image: postgres:14.1-alpine
   container_name: postgres
   hostname: postgres
   restart: always
   ports:
    - "5432:5432"   
   environment:
     POSTGRES_DB: TARGET_DB
     POSTGRES_USER: root
     POSTGRES_PASSWORD: 123456